wealdtech/chaind

- CHANGELOG
- main.go
- schema.sql
- services/beaconcommittees/standard/parameters.go
- services/chaindb/postgresql/upgrader.go
- services/chaindb/postgresql/validators.go
- services/chaindb/postgresql/validators_test.go
V1 of chaind used '-1' to mark a validator epoch column as
FAR_FUTURE_EPOCH.  The actual value of FAR_FUTURE_EPOCH is not
compatible with the PostgreSQL 'BIGINT' column, as it is outside of its
range.  Although -1 worked, it made querying the database harder than it
needed to be with multiple constraints, and could cause confusion with
differing definitions of the conditions for states.
This change alters the schema of t_validators to allow NULL values in
the relevant columns, and updates existing values of FAR_FUTURE_EPOCH to
be NULL.
This change also introduces a generic database upgrader, which is used
to carry out the required changes to the database schema and data.  The
upgrader can be used for additional changes in the schema as V2
progresses.
> Use NULL for validator columns; add upgrader.

- CHANGELOG
- main.go
- schema.sql
- services/chaindb/postgresql/chainspec.go
- services/chaindb/postgresql/chainspec_test.go
- services/chaindb/postgresql/genesis.go
- services/chaindb/postgresql/genesis_test.go
- services/chaindb/postgresql/spec.go
- services/chaindb/postgresql/spec_test.go
- services/chaindb/postgresql/upgrader.go
- services/chaindb/service.go
- services/spec/standard/parameters.go
- services/spec/standard/service.go
This adds two parameter tables: `f_chain_spec` and `f_genesis`.  `f_chain_spec` contains the specification for the chain, as per the
Ethereum 2.0 specifications document.  `f_genesis` contains information about the genesis of the chain.
> Add parameter tables.

- CHANGELOG
- README.md
- clients.go
- logging.go
- main.go
- services/beaconcommittees/standard/service.go
- services/blocks/standard/service.go
- services/chaindb/postgresql/service.go
- services/chaintime/standard/service.go
- services/proposerduties/standard/service.go
- services/validators/standard/service.go
- util/logging.go
This change makes configuration of log levels using the `log-level` configuration parameters hierarchical.  For example, given a path in dot notation `a.b`, the following configuration variables will be searched for a value:
- `a.b.log-level`
- `a.log-level`
- `log-level`
The first variable containing a value will be used.
This allows for simple setting of the global level with individual as well as group overrides.
> Make log levels hierarchical.

- CHANGELOG
- schema.sql
- services/blocks/standard/handler.go
- services/blocks/standard/service.go
- services/chaindb/postgresql/attestations.go
- services/chaindb/postgresql/upgrader.go
- services/chaindb/types.go
- util/logging.go
This change adds a field to attestations, providing the indices of the validators that were part of the attestation.  This is useful, as it
avoids users having to parse a bitlist using beacon committee information.
> Add f_aggregation_indices to t_attestations

- CHANGELOG
- services/chaindb/postgresql/aggregatevalidatorbalances.go
- services/chaindb/service.go
- services/chaindb/types.go
This adds functions to obtain aggregate validator balances, as an AggregateValidatorBalancesProvider interface.  By mirroring the
unaggregated functions it allows for a significant reduction in the time taken to obtain simple aggregate validator metrics.
> Add aggregate validator balance functions.

- CHANGELOG
- schema.sql
- services/chaindb/postgresql/attestations.go
- services/chaindb/postgresql/upgrader.go
- services/chaindb/service.go
- services/chaindb/types.go
- services/finalizer/standard/handler.go
- services/finalizer/standard/handler_internal_test.go
- services/finalizer/standard/metadata.go
- services/finalizer/standard/service.go
- services/finalizer/standard/service_test.go
This change adds the fields `f_target_correct` and `f_head_correct` to the `t_attestations` table.  It also adds code to the finalizer that augments attestations with details of the correctness of their target and head votes.  It attempts to do this as finality information is obtained, as well as on start-up.
Because modules in chaind are loosely coupled, it is possible for the finalizer to not have the required information in the chaind database to carry out its operations.  In these situations it will retry incrementally at each new finality checkpoint, as for all indeterminate attestations on start-up.
> Add vote finalizer.

- CHANGELOG
- docs/prometheus.md
- go.mod
- go.sum
- main.go
- metrics.go
- services/beaconcommittees/standard/handler.go
- services/beaconcommittees/standard/metrics.go
- services/beaconcommittees/standard/parameters.go
- services/beaconcommittees/standard/service.go
- services/blocks/standard/handler.go
- services/blocks/standard/metrics.go
- services/blocks/standard/parameters.go
- services/blocks/standard/service.go
- services/finalizer/standard/handler.go
- services/finalizer/standard/metrics.go
- services/finalizer/standard/parameters.go
- services/finalizer/standard/service.go
- services/metrics/null/service.go
- services/metrics/prometheus/parameters.go
- services/metrics/prometheus/service.go
- services/metrics/service.go
- services/proposerduties/standard/handler.go
- services/proposerduties/standard/metrics.go
- services/proposerduties/standard/parameters.go
- services/proposerduties/standard/service.go
- services/validators/standard/handler.go
- services/validators/standard/metrics.go
- services/validators/standard/parameters.go
- services/validators/standard/service.go
This patch adds prometheus metrics for all modules, providing information about the number of slots or epochs processed as well as the latest slot or epoch processed.  It also provides release metrics.
> Add metrics.

- main.go
- services/eth1deposits/getlogs/blocknumber.go
- services/eth1deposits/getlogs/blocktimestampbyhash.go
- services/eth1deposits/getlogs/chainid.go
- services/eth1deposits/getlogs/getlogs.go
- services/eth1deposits/getlogs/http.go
- services/eth1deposits/getlogs/service.go
- services/eth1deposits/getlogs/transactionbyhash.go
- services/eth1deposits/getlogs/transactionreceiptbyhash.go
HTTP requests in the eth1deposits module used individual code to make their calls.  This change provides a single call that is standardised across the methods.  It also ensures that connections are closed in a timely fashion, avoiding potential resource exhaustion.
> Standardise HTTP requests.

- CHANGELOG
- main.go
Check that the chain has started and that the node is synced before starting to attempt to collect data.
> Ensure node is in suitable state before starting.

- CHANGELOG
- main.go
- services/beaconcommittees/standard/handler.go
- services/beaconcommittees/standard/service.go
- services/blocks/standard/handler.go
- services/blocks/standard/service.go
- services/proposerduties/standard/handler.go
- services/proposerduties/standard/service.go
- services/summarizer/standard/block.go
- services/summarizer/standard/handler.go
This patch changes the behaviour of chaind in the face of a failure to obtain data from "mark as missed and carry on" to "stop this attempt at data collection".  With the subsequent introduction of the finalizer and summarizer the former behaviour can result in incorrect summaries, whereas the latter can result in delayed summaries.  The latter is preferable.
> Fail fast if data unavailable.

- CHANGELOG
- go.mod
- go.sum
- services/chaindb/postgresql/forkschedule.go
- services/chaindb/postgresql/parameters.go
- services/chaindb/postgresql/service.go
This deprecates the simple URL method and instead uses individual paramters for values such as server, port, username and password.  It also allows configuration of TLS connections, using certificates to provide mutual authentication.
> Provide individual parameters for connection.

- CHANGELOG
- services/chaindb/postgresql/service_test.go
- services/chaindb/postgresql/validatorepochsummaries.go
- services/chaindb/postgresql/validators.go
- services/chaindb/service.go
- services/summarizer/standard/epoch.go
- services/summarizer/standard/validatorepoch.go
- services/validators/standard/handler.go
Use bulk insert for validator balances and validator epoch summaries, which significantly increases insertion speed.
> Use bulk insert where appropriate.

- README.md
We found this one out the hard way. 
With the default SPRP of 2048, if chaind queries Lighthouse for a slot 1000+ slots away from the checkpoint the response time can exceed 1 minute. This makes indexing extremely slow.
On the other hand, an SPRP of 64 currently needs ~600GB of disk space. The user needs to be aware of this trade-off.
> Add Lighthouse instruction

- CHANGELOG
- services/chaintime/service.go
- services/chaintime/standard/service.go
- services/synccommittees/standard/handler.go
- services/synccommittees/standard/service.go
If the first block of sync committee period is missed then the sync committee data is not obtained.  This checks on each slot to see if the sync committee period is ahead of our latest fetched period to ensure that they are fetched at the first opportunity.
> Fix missed sync committee information.

- services/finalizer/standard/handler.go
When an epoch is finalized then the attestations in the epoch should be finalized.  The code was finalizing attestations for the epoch, which is incorrect as attestations for the last block will be in a non-finalized epoch and generate errors.
> Finalize attestations in epoch, not for epoch.

- services/blocks/standard/metrics.go
- services/finalizer/standard/metrics.go
- services/summarizer/standard/metrics.go
Always check for initialisation of prometheus metrics prior to use.
Fixes #45
> Avoid uninitialised metrics.

- services/chaindb/postgresql/validators.go
- services/chaindb/service.go
- services/summarizer/standard/epoch.go
The epoch summarizer runs a select on the `t_validator_balances` table
with a filter like `f_validator_index = ANY(ARRAY[...])` where the array
lists all active validators (~400k at this time). This is taking a
long time to complete.
To speed things up, rather than pass this huge array in the query,
fetch all rows and do the filtering in chaind.
On my setup I'm seeing epoch summaries computed in few seconds (vs
several minutes previously).
fixes #49
> Speed up epoch summaries

- CHANGELOG.md
- services/eth1deposits/getlogs/handler.go
Avoid crash when execution node does not return transaction for which it supplied a log entry.
Fixes #55.
> Avoid crash on missing execution tx.

- CHANGELOG.md
- services/chaindb/postgresql/parameters.go
- services/chaindb/postgresql/upgrader.go
If the in-database schema version is ahead of the version the code expects then print a warning.
> Check and warn schema version.

- Dockerfile
This seemingly solves for https://github.com/wealdtech/chaind/issues/69
> update Dockerfile to utilize go 1.18

- services/chaindb/postgresql/blstoexecutionchanges.go
- services/chaindb/postgresql/upgrader.go
- services/chaindb/postgresql/validators.go
- services/chaindb/types.go
- services/validators/standard/handler.go
This PR implements the changes proposed in https://github.com/wealdtech/chaind/issues/78#issuecomment-1423810954
We did not do extensive testing of these changes, but they seem to be working fine when indexing zhejiang. Let us know if there's anything we got wrong or that we can improve.
> Add history of validator's withdrawal credentials

- README.md
I think chaind needs lighthouse to be started with the `--reconstruct-historic-states` flag.
Sproul in the lighthouse discord [mentioned](https://discord.com/channels/605577013327167508/605577013331361793/1087537928449831032)
Otherwise none of the historic states before the checkpoint slot are ever stored (`--slots-per-restore-point` only affects slots after the checkpoint slot without `--reconstruct-historic-states`).
> Bug: missing flag for lighthouse historic state

- main.go
If `OpenFile` inside `initLogging` fails for whatever reason, e.g. Permission Denied, global var `log` remains uninitialized, which makes the error message not to be printed to stdout.
> failure to open log-file does not show an error

- services/summarizer/standard/validatorday.go
> Do not fetch sync committees prior to Altair.
